### ISSUE TITLE
请问父类怎么选择？

### ISSUE THREAD

**Issue by 851091009** [yujinpan/el-select-tree#1]

**Comment by yujinpan** [comment]
Hi，感谢反馈，我加入了一个新的参数 `checkStrictly`，类似 element-ui 的级联选择器，它为 `true` 时将可以选择任何一级。
详情请查看文档：https://github.com/yujinpan/el-select-tree#attributes

**Comment by yujinpan** [comment]
你可以在新的实例中试一下：

**Comment by 851091009** [comment]
非常感谢！
