### ISSUE TITLE
关于树下拉选择过滤功能

### ISSUE THREAD

**Issue by tenPunchSuperman** [yujinpan/el-select-tree#11]
你好，我想问问，后期el-select-tree是否会打算新增一个 filterable 属性，以支持可输入过滤选择功能， 例如树的filter-method方法
![Uploading image.png…]()

**Comment by yujinpan** [comment]
Hi，此功能模仿 `el-select` 的交互稍复杂，后期会加。

**Comment by pengzhongyan** [comment]
此功能啥时候添加呢？

**Comment by yujinpan** [comment]
新版本 2.0 已经发布，过滤功能已加上，欢迎使用。
