### ISSUE TITLE
1.0.23支持ie11，不支持ie10和ie9

### ISSUE THREAD

**Issue by yy306525121** [yujinpan/el-select-tree#13]
SCRIPT1002: 语法错误
chunk-4721db7e.30b0efc7.js (17,2099)

elect-tree v1.0.23
 * (c) 2019-2020 yujinpan
 * Released under the MIT License.
 */function h(e,t){void 0===t&&(t={});var r=t.insertAt;if(e&&"undefined"!==typeof document){var n=document.head||document.getElementsByTagName("head")[0],i=document.createElement("style");i.type="text/css","top"===r&&n.firstChild?n.insertBefore(i,n.firstChild):n.appendChild(i),i.styleSheet?i.styleSheet.cssText=e:i.appendChild(document.createTextNode(e))}}var v=".el-select-tree{display:inline-block}.el-select-tree .el-input__icon{cursor:pointer;-webkit-transition:-webkit-transform .3s;transition:-webkit-transform .3s;transition:transform .3s;transition:transform .3s,-webkit-transform .3s}.el-select-tree .el-input__icon-close{display:none}.el-select-tree .el-input__inner{cursor:pointer;padding-right:30px}.el-select-tree .el-input:hover:not(.is-disabled) .el-input__inner{border-color:#c0c4cc}.el-select-tree .el-input:hover:not(.is-disabled).is-selected.is-clearable .el-input__icon-close{display:inline-block}.el-select-tree .el-input:hover:not(.is-disabled).is-selected.is-clearable .el-input__icon-arrow-down{display:none}.el-select-tree .el-input.is-active .el-input__icon-arrow-down{-webkit-transform:rotate(-180deg);-ms-transform:rotate(-180deg);transform:rotate(-180deg)}.el-select-tree .el-input.is-active .el-input__inner{border-color:#409eff}.el-select-tree__popover{padding:0!important;border:1px solid #e4e7ed!important;border-radius:4px!important}.el-select-tree__popover .popper__arrow{left:35px!important}.el-select-tree__popover .el-tree-node__expand-icon.is-leaf{cursor:pointer}.el-select-tree__list{overflow-y:auto}.el-select-tree__list::-webkit-scrollbar-track-piece{background:#d3dce6}.el-select-tree__list::-webkit-scrollbar{width:4px}.el-select-tree__list::-webkit-scrollbar-thumb{background:#99a9bf}.el-select-tree__item{position:relative;white-space:nowrap;padding-right:20px}.el-select-tree__item.selected{color:#409eff;font-weight:bolder}.el-select-tree__item.is-disabled{color:#bbb;cursor:not-allowed}.el-select-tree__empty{padding:10px 0;margin:0;text-align:center;color:#999;font-size:14px}";function b(e,t,r,n,i,l,a,o,c,s){"boolean"!==typeof a&&(c=o,o=a,a=!1);const u="function"===typeof r?r.options:r;let d;if(e&&e.render&&(u.render=e.render,u.staticRenderFns=e.staticRenderFns,u._compiled=!0,i&&(u.functional=!0)),n&&(u._scopeId=n),l?(d=function(e){e=e||this.$vnode&&this.$vnode.ssrContext||this.parent&&this.parent.$vnode&&this.parent.$vnode.ssrContext,e||"undefined"===typeof __VUE_SSR_CONTEXT__||(e=__VUE_SSR_CONTEXT__),t&&t.call(this,c(e)),e&&e._registeredComponents&&e._registeredComponents.add(l)},u._ssrRegister=d):t&&(d=a?function(e){t.call(this,s(e,this.$root.$options.shadowRoot))}:function(e){t.call(this,o(e))}),d)if(u.functional){const e=u.render;u.render=function(t,r){return d.call(r),e(t,r)}}else{const e=u.beforeCreate;u.beforeCreate=e?[].concat(e,d):[d]}return r}h(v);"undefined"!==typeof navigator&&/msie [6-9]\\b/.test(navigator.userAgent.toLowerCase());var g=p,_=function(){var e=this,t=e.$createElement,r=e._self._c||t;return r("div",{staticClass:"el-select-tree"},[r("el-popover",{ref:"elPopover",attrs:{transition:"el-zoom-in-top","popper-class":"el-select-tree__popover",trigger:"click",disabled:e.disabled,placement:e.placement},on:{"after-enter":function(t){return e.handleScroll()}},model:{value:e.visible,callback:function(t){e.visible=t},expression:"visible"}},[e.dataLength?r("el-scrollbar",{ref:"scrollbar",class:{"is-empty":0===e.dataLength},attrs:{"wrap-class":"el-select-dropdown__wrap","view-class":"el-select-dropdown__list"}},[r("el-tree",{ref:"elTree",staticClass:"el-select-tree__list",style:{"min-width":e.minWidth+"px"},attrs:{"default-expand-all":e.defaultExpandAll,props:e.props,"node-key":e.propsValue,"show-checkbox":e.multiple,"expand-on-click-node":e.multiple,data:e.data,"default-expanded-keys":e.defaultExpandedKeys,"check-strictly":e.checkStrictly},on:{"node-click":e.nodeClick,"check-change":e.checkChange},scopedSlots:e._u([{key:"default",fn:function(t){var n=t.data;return r("div",{staticClass:"el-select-tree__item",class:e.treeItemClass(n)},[e._v("\n          "+e._s(n[e.propsLabel])+"\n        ")])}}],null,!1,1229176757)})],1):r("p",{staticClass:"el-select-tree__empty",style:{width:e.minWidth+"px"}},[e._v("\n      无数据\n    ")]),r("el-input",{ref:"reference",class:{"is-active":e.visible,"is-selected":e.selectedLabel,"is-clearable":e.clearable},attrs:{slot:"reference",readonly:"","validate-event":!1,size:e.size,disabled:e.disabled,placeholder:e.placeholder},slot:"reference",model:{value:e.selectedLabel,callback:function(t){e.selectedLabel=t},expression:"selectedLabel"}},[e.clearable?r("i",{staticClass:"el-input__icon el-input__icon-close el-icon-circle-close",attrs:{slot:"suffix"},on:{click:function(t){return t.stopPropagation(),e.clear()}},slot:"suffix"}):e._e(),r("i",{staticClass:"el-input__icon el-input__icon-arrow-down el-icon-arrow-down",attrs:{slot:"suffix"},slot:"suffix"})])],1)],1)},y=[],m=void 0,x=void 0,S=void 0,w=!1,k=b({render:_,staticRenderFns:y},m,g,x,w,S,!1,void 0,void 0,void 0);k.install=function(e){e.component("ElSelectTree",k)};t["a"]=k},"8b97":function(e,t,r){var n=r("d3f4"),i=r("cb7c"),l=function(e,t){if(i(e),!n(t)&&null!==t)throw TypeError(t+": can't set as prototype!")};e.exports={set:Object.setPrototypeOf||("__proto__"in{}?function(e,t,n){try{n=r("9b43")(Function.call,r("11e9").f(Object.prototype,"__proto__").set,2),n(e,[]),t=!(e instanceof Array)}catch(i){t=!0}return function(e,r){return l(e,r),t?e.__proto__=r:n(e,r),e}}({},!1):void 0),check:l}},9744:function(e,t,r){"use strict";var n=r("4588"),i=r("be13");e.exports=function(e){var t=String(i(this)),r="",l=n(e);if(l<0||l==1/0)throw RangeError("Count can't be negative");for(;l>0;(l>>>=1)&&(t+=t))1&l&&(r+=t);return r}},a481:function(e,t,r){"use strict";var n=r("cb7c"),i=r("4bf8"),l=r("9def"),a=r("4588"),o=r("0390"),c=r("5f1b"),s=Math.max,u=Math.min,d=Math.floor,f=/\$([$&`']|\d\d?|<[^>]*>)/g,p=/\$([$&`']|\d\d?)/g,h=function(e){return void 0===e?e:String(e)};r("214f")("replace",2,(function(e,t,r,v){return[function(n,i){var l=e(this),a=void 0==n?void 0:n[t];return void 0!==a?a.call(n,l,i):r.call(String(l),n,i)},function(e,t){var i=v(r,e,this,t);if(i.done)return i.value;var d=n(e),f=String(this),p="function"===typeof t;p||(t=String(t));var g=d.global;if(g){var _=d.unicode;d.lastIndex=0}var y=[];while(1){var m=c(d,f);if(null===m)break;if(y.push(m),!g)break;var x=String(m[0]);""===x&&(d.lastIndex=o(f,l(d.lastIndex),_))}for(var S="",w=0,k=0;k<y.length;k++){m=y[k];for(var E=String(m[0]),C=s(u(a(m.index),f.length),0),A=[],T=1;T<m.length;T++)A.push(h(m[T]));var $=m.groups;if(p){var R=[E].concat(A,C,f);void 0!==$&&R.push($);var I=String(t.apply(void 0,R))}else I=b(E,f,C,A,$,t);C>=w&&(S+=f.slice(w,C)+I,w=C+E.length)}return S+f.slice(w)}];function b(e,t,n,l,a,o){var c=n+e.length,s=l.length,u=p;return void 0!==a&&(a=i(a),u=f),r.call(o,u,(function(r,i){var o;switch(i.charAt(0)){case"$":return"$";case"&":return e;case"`":return t.slice(0,n);case"'":return t.slice(c);case"<":o=a[i.slice(1,-1)];break;default:var u=+i;if(0===u)return r;if(u>s){var f=d(u/10);return 0===f?r:f<=s?void 0===l[f-1]?i.charAt(1):l[f-1]+i.charAt(1):r}o=l[u-1]}return void 0===o?"":o}))}}))},aa77:function(e,t,r){var n=r("5ca1"),i=r("be13"),l=r("79e5"),a=r("fdef"),o="["+a+"]",c="​",s=RegExp("^"+o+o+"*"),u=RegExp(o+o+"*$"),d=function(e,t,r){var i={},o=l((function(){return!!a[e]()||c[e]()!=c})),s=i[e]=o?t(f):a[e];r&&(i[r]=s),n(n.P+n.F*o,"String",i)},f=d.trim=function(e,t){return e=String(i(e)),1&t&&(e=e.replace(s,"")),2&t&&(e=e.replace(u,"")),e};e.exports=d},aae3:function(e,t,r){var n=r("d3f4"),i=r("2d95"),l=r("2b4c")("match");e.exports=function(e){var t;return n(e)&&(void 0!==(t=e[l])?!!t:"RegExp"==i(e))}},aef6:function(e,t,r){"use strict";var n=r("5ca1"),i=r("9def"),l=r("d2c8"),a="endsWith",o=""[a];n(n.P+n.F*r("5147")(a),"String",{endsWith:function(e){var t=l(this,e,a),r=arguments.length>1?arguments[1]:void 0,n=i(t.length),c=void 0===r?n:Math.min(i(r),n),s=String(e);return o?o.call(t,s,c):t.slice(c-s.length,c)===s}})},b0c5:function(e,t,r){"use strict";var n=r("520a");r("5ca1")({target:"RegExp",proto:!0,forced:n!==/./.exec},{exec:n})},c5f6:function(e,t,r){"use strict";var n=r("7726"),i=r("69a8"),l=r("2d95"),a=r("5dbc"),o=r("6a99"),c=r("79e5"),s=r("9093").f,u=r("11e9").f,d=r("86cc").f,f=r("aa77").trim,p="Number",h=n[p],v=h,b=h.prototype,g=l(r("2aeb")(b))==p,_="trim"in String.prototype,y=function(e){var t=o(e,!1);if("string"==typeof t&&t.length>2){t=_?t.trim():f(t,3);var r,n,i,l=t.charCodeAt(0);if(43===l||45===l){if(r=t.charCodeAt(2),88===r||120===r)return NaN}else if(48===l){switch(t.charCodeAt(1)){case 66:case 98:n=2,i=49;break;case 79:case 111:n=8,i=55;break;default:return+t}for(var a,c=t.slice(2),s=0,u=c.length;s<u;s++)if(a=c.charCodeAt(s),a<48||a>i)return NaN;return parseInt(c,n)}}return+t};if(!h(" 0o1")||!h("0b1")||h("+0x1")){h=function(e){var t=arguments.length<1?0:e,r=this;return r instanceof h&&(g?c((function(){b.valueOf.call(r)})):l(r)!=p)?a(new v(y(t)),r,h):y(t)};for(var m,x=r("9e1e")?s(v):"MAX_VALUE,MIN_VALUE,NaN,NEGATIVE_INFINITY,POSITIVE_INFINITY,EPSILON,isFinite,isInteger,isNaN,isSafeInteger,MAX_SAFE_INTEGER,MIN_SAFE_INTEGER,parseFloat,parseInt,isInteger".split(","),S=0;x.length>S;S++)i(v,m=x[S])&&!i(h,m)&&d(h,m,u(v,m));h.prototype=b,b.constructor=h,r("2aba")(n,p,h)}},d2c8:function(e,t,r){var n=r("aae3"),i=r("be13");e.exports=function(e,t,r){if(n(t))throw TypeError("String#"+r+" doesn't accept regex!");return String(i(e))}},f576:function(e,t,r){"use strict";var n=r("5ca1"),i=r("2e08"),l=r("a25f"),a=/Version\/10\.\d+(\.\d+)?( Mobile\/\w+)? Safari\//.test(l);n(n.P+n.F*a,"String",{padStart:function(e){return i(this,e,arguments.length>1?arguments[1]:void 0,!0)}})},fdef:function(e,t){e.exports="\t\n\v\f\r   ᠎             　\u2028\u2029\ufeff"}}]);

**Comment by yujinpan** [comment]
Hi，你可以用 ie9 访问实例网站 https://yujinpan.github.io/el-select-tree ，它是没有兼容问题的。
因为它是 es 模块，考虑是项目的兼容性配置问题。请参考实例项目中的配置：
https://github.com/yujinpan/el-select-tree/blob/dee462cb322670fd6fc600a486b2dc332ba19005/package.json#L66-L70
