### ISSUE TITLE
楼主你好，我看了下你的源码，触发事件的回调的参数有点少呀，没有树形带的Node,data什么的吗

### ISSUE THREAD

**Issue by storagess** [yujinpan/el-select-tree#18]
楼主你好，我看了下你的源码，触发事件的回调的参数有点少呀，没有树形带的Node,data什么的吗

**Comment by storagess** [comment]
作者，通过NPM 安装你的包后可以修改源码吗？并没有发现有源码文件

**Comment by yujinpan** [comment]
👋

触发事件是单一的 v-model 绑定的值，没有携带树节点的信息，要获取树节点的信息可以先这样（后面会加一些辅助方法）：
1. 在树里面通过key自己查（建一个索引）
2. 通过`$refs.elSelectTree.$refs.elTree`获取是树组件的实例，再使用它的方法`getNode`用key去查

源码没有放到打包后的目录里（占体积），即使放了，修改也是没有用的，你可以 fork 后自定义修改。

**Comment by storagess** [comment]
@yujinpan  好的谢谢，目前我是把你的源码拷到项目中了。并在触发事件里面加了el-tree的nodeclick的回调参数
