### ISSUE TITLE
编辑的时候，tree 没有自动展开 (图示)

### ISSUE THREAD

**Issue by 851091009** [yujinpan/el-select-tree#2]
![1](https://user-images.githubusercontent.com/8460036/69684421-97513380-10f3-11ea-9019-3f42026dda48.gif)

**Comment by yujinpan** [comment]
感谢再次反馈，我增加了默认值的展开，请更新版本至 v1.0.9。
请查看实例：https://yujinpan.github.io/el-select-tree/
