### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by storagess** [yujinpan/el-select-tree#20]
我配置了懒加载但是并没有任何效果

**Comment by yujinpan** [comment]
是否初始化有默认的数据？看看这个实例：https://codesandbox.io/s/el-select-tree-lazy-load-hl2fj?file=/src/components/HelloWorld.vue

**Comment by storagess** [comment]
@yujinpan  因为我使用的el-tree 初始化的并没有数据，会自动执行load的函数加载第一级 。所以 使用你的组件的时候我并没有初始化任何数据data

**Comment by yujinpan** [comment]
已修复，请更新至最新版本 1.0.27。

- 实例已加上懒加载 https://yujinpan.github.io/el-select-tree/
- 修复详情 https://github.com/yujinpan/el-select-tree/commit/9b879957109546364b799546f4989b2fdcf04b58
