### ISSUE TITLE
props在jsx 中无法合并

### ISSUE THREAD

**Issue by gongxiansheng** [yujinpan/el-select-tree#23]
`
treeProps: {
        children: 'children',
        label: 'name',
        value: 'id'
    }
 render: (h, form) => (
            <el-select-tree
                placeholder='请选择部门'
                data={this.treeData}
                props={this.treeProps}
                v-model={form.orgId}
                default-expand-all={true}
                check-strictly
            ></el-select-tree>
        )
`
在jsx中并未进行合并props

**Comment by yujinpan** [comment]
JSX 中 `props` 需要这样写：

```jsx
const props = { children: 'children' };
const bind = {
  props: {
    ...props
  },
  on: {
    change() {}
  }
}
const render = () => <el-select-tree {...bind} />
```

更多实例在这里：https://github.com/vuejs/jsx#attributesprops

**Comment by gongxiansheng** [comment]
thanks，

> const bind = {
                            props: {
                                ...this.treeProps
                            },
                            data: this.treeData,
                            defaultExpandAll: true,
                            checkStrictly: true,
                            renderContent: this.renderContent
                        }
                        return (
                            <el-select-tree
                                style='width:100%'
                                {...{ attrs: bind }}
                                vModel={form.orgId}
                                placeholder='请选择部门'
                                clearable
                            />
                        )
