### ISSUE TITLE
props的几个参数好像不支持function类型

### ISSUE THREAD

**Issue by kooriookami** [yujinpan/el-select-tree#29]
作者你好，我尝试使用props的function类型，如下图，似乎不会生效。
![image](https://user-images.githubusercontent.com/38392315/141895952-b38f68ab-8b8b-4769-a6a3-dd7cc8eaf8b6.png)

还有一个小问题是v-model绑定的参数是对象中不存在的属性，组件就报错了。
比如`<el-select-tree v-model="form.id" :data="[]"></el-select-tree>`，其中form是一个空对象。

**Comment by yujinpan** [comment]
版本 2.0.3 已经发布，此功能已支持。
