### ISSUE TITLE
数据key值自定义问题

### ISSUE THREAD

**Issue by yunpenghu** [yujinpan/el-select-tree#3]
当数据的key值不一样时子类无法选择

如：              <el-select-tree
                        placeholder="请选择"
                        :data="treeList"
                        :props="defaultProps"
                        v-model="ruleForm.productTypeId"
                        >
                     </el-select-tree>

                    defaultProps: {
                      children: 'list',
                      value: 'id',
                      label: 'name'
                    },
 后面看组件  发现treeFind.esm.js 里面children写死了 修改children为list  问题解决

**Comment by yujinpan** [comment]
感谢反馈！该问题在新版(v1.0.12)中已经修复，请更新一下。

具体修复内容请查看：
https://github.com/yujinpan/el-select-tree/commit/2bf8e0c087eaf658d2ec9337c97a838ef88a0f52#diff-72a67d3abcafefb0332e7c656461154dL212

**Comment by yujinpan** [comment]
🤓  请更新至 v1.0.13 !
