### ISSUE TITLE
当props设置label后，filterable搜索报错

### ISSUE THREAD

**Issue by kooriookami** [yujinpan/el-select-tree#30]
![image](https://user-images.githubusercontent.com/38392315/141932092-a79ee04a-fa16-4c8b-a437-3d17fad9768f.png)
看报错原因，应该是当prop指定label为别的字段时候，搜索的时候依然用的label字段去搜，所以报错

**Comment by kooriookami** [comment]
还有一个细节哈，就是当下拉菜单打开时，应该重置搜索状态，不然树就只剩一段了ORZ

**Comment by yujinpan** [comment]
感谢反馈，会尽快出个小版本解决这些问题。

**Comment by kooriookami** [comment]
> 还有一个细节哈，就是当下拉菜单打开时，应该重置搜索状态，不然树就只剩一段了ORZ

@yujinpan  要是方便的话，可以先把这个问题修复发个小版本嘛

**Comment by yujinpan** [comment]
已经修改了，今天晚点发布。

**Comment by kooriookami** [comment]
> 已经修改了，今天晚点发布。

感谢感谢

**Comment by yujinpan** [comment]
版本 2.0.3 已经发布，此问题已修复。

**Comment by kooriookami** [comment]
刚刚用了，很完美，感谢开发者提供这么好的一个组件~
