### ISSUE TITLE
是否计划增加树得复选框？

### ISSUE THREAD

**Issue by yaoshiyang** [yujinpan/el-select-tree#31]

**Comment by yujinpan** [comment]
select 是点击选择，与复选框的操作不相同。在 2.0 版本中统一了，使用点选操作。

可以降级至 1.0 版本，旧版本用的是复选框。

**Comment by kooriookami** [comment]
> select 是点击选择，与复选框的操作不相同。在 2.0 版本中统一了，使用点选操作。
> 
> 可以降级至 1.0 版本，旧版本用的是复选框。

数据很多的话，全选某个节点就比较麻烦了，100个子节点，用户就要点100次。Antd的树选择也是有复选框呢，我觉得这是挺重要的。
![image](https://user-images.githubusercontent.com/38392315/142711442-4304c975-c708-46c4-91fd-05b1d97db022.png)

**Comment by yujinpan** [comment]
确实！会尽快在新版中将此功能完善。

**Comment by kooriookami** [comment]
十分感谢~

**Comment by yujinpan** [comment]
版本 2.0.3 已经发布，此功能已添加。
