### ISSUE TITLE
关于popper-append-to-body的使用问题

### ISSUE THREAD

**Issue by kooriookami** [yujinpan/el-select-tree#32]
首先感谢一下开发者的贡献，在使用过程中发现一些影响使用的问题，在此列出。
![image](https://user-images.githubusercontent.com/38392315/143355568-3e890f52-d35f-4d8a-8f47-b80e6d186ed2.png)
这张图上可以看到2个问题。
第一个问题比较严重，是选择树的popover超过组件范围时，多出部分会被截断，原生的`el-select`组件对于此场景效果是正常的。此时我想到`popper-append-to-body`属性，然后发现popover中树的样式会错乱，原因是`.el-select-tree`class下的样式没有被识别到。建议和element ui一样，`popper-append-to-body`默认为`true`，然后改为样式全局。
![image](https://user-images.githubusercontent.com/38392315/143358209-db5a4bc5-2bab-4e04-b1e0-37341a72d69e.png)
![image](https://user-images.githubusercontent.com/38392315/143364807-d5c2b26e-61ee-4382-9f6e-b8642a0f2cfe.png)
第二个是个小问题，用户也可以自己覆盖，我提一下。`placeholder`似乎没有适应element ui中的国际化，在`el-select-tree/src/components/utils.ts` 34行，代码中`placeholder`的默认值写死的是中文`请选择`，我想如果不给与它默认值，是不是会使用element ui自带值呢。

**Comment by yujinpan** [comment]
👍，尽快修复此问题。

**Comment by yujinpan** [comment]
此问题在 2.0.4 中已修复。

**Comment by kooriookami** [comment]
感谢，关闭此issue
