### ISSUE TITLE
设置为懒加载后自动调用load方法

### ISSUE THREAD

**Issue by Montaro2017** [yujinpan/el-select-tree#36]
将组件设置为lazy后，组件创建后会自动调用懒加载的load方法哪怕里面没有节点
但是在此前系统有些数据还没加载完成，导致load会出现缺少数据的情况

希望能增加一个是否自动调用load的属性

**Comment by yujinpan** [comment]
您好，由于继承了 el-tree 组件功能，使用上类似直接使用 el-tree，不宜增加其他业务方面的功能。

此类情况建议预先处理。

即前置数据获取到后再渲染 el-select-tree 组件，例如使用 `v-if="preData"` 控制渲染。
