### ISSUE TITLE
事件event不起作用

### ISSUE THREAD

**Issue by jianchenc** [yujinpan/el-select-tree#39]
只有change事件起作用，其他事件均不起作用；
通过什么事件能获取到当前选中节点的对象，而不单单是一个数值，比如 单选，选到了子类，但是同时我也想那的的父节点信息，如何实现？node-click等事件均不为触发，请问如何调用其他事件??当前有没有能满足我需求的事件？请赐教

**Comment by yujinpan** [comment]
通过 `ref` 可以访问 `el-tree` 的实例，然后调用 `getNode` 或者 `getCheckedNodes` 获取勾选的节点。

> 更多方法查看：https://element.eleme.io/#/zh-CN/component/tree#fang-fa

```vue
<template>
  <el-select-tree ref="selectTree" v-model="value" />
</template>

<script>
export default {
  computed: {
    currentNode() {
      return this.$refs.selectTree.tree.getNode(this.value);
    }
  }
}
</script>
```

**Comment by problemking** [comment]
请问怎么通过点击节点，通过选中得值添加相应得逻辑那，那些事件都不好使

**Comment by DLGDark** [comment]
> 通过 `ref` 可以访问 `el-tree` 的实例，然后调用 `getNode` 或者 `getCheckedNodes` 获取勾选的节点。
> 
> > 更多方法查看：https://element.eleme.io/#/zh-CN/component/tree#fang-fa
> 
> ```
> <template>
>   <el-select-tree ref="selectTree" v-model="value" />
> </template>
> 
> <script>
> export default {
>   computed: {
>     currentNode() {
>       return this.$refs.selectTree.tree.getNode(this.value);
>     }
>   }
> }
> </script>
> ```

上面的方法有问题，下面正确使用：
子组件(封装公用组件中)：
```
<el-select-tree ref="selectTreeCommonRef" v-model="defaultVal" @change="valueChange"  />

valueChange(val) {
  this.$emit("change", val);
  // 获取当前选中值的节点
  let currentNode = this.$refs.selectTreeCommonRef.$refs.elTree.getNode(this.defaultVal);
  this.$emit("getCurrentNode", currentNode);
},
```

父组件：
```
getCurrentNode(curNode) {
   console.log(curNode)
},
```

**Comment by Kim1am** [comment]
你好，目前@focus并不起作用
`             
 <ElSelectTree
                v-model="searchForm.officeCode"
                clearable
                @focus="getCurrentUserOffices"
                :data="officeCodeList"
              >
              </ElSelectTree>
    getCurrentUserOffices() {
      console.log(1111111)
    }
`

**Comment by yujinpan** [comment]
感谢反馈！尽快修复！

**Comment by yujinpan** [comment]
所有事件的 ElSelect/ElTree 事件与实例方法都已加上。

```vue
<template>
  <!-- ElSelect/ElTree 原生事件都已支持 -->
  <el-select-tree ref="selectTree" v-model="value" @change @check @nodeClick />
</template>

<script>
export default {
  data() {
     value: ''
  },
  computed: {
    currentNode() {
      // getNode 等所有实例方法直接调用
      return this.$refs.selectTree?.getNode(this.value);
    }
  }
}
</script>
```
