### ISSUE TITLE
懒加载后数据回显有问题是否有好的解决方法

### ISSUE THREAD

**Issue by Montaro2017** [yujinpan/el-select-tree#45]
![image](https://user-images.githubusercontent.com/35142778/165425869-6836c060-d42b-45b9-882d-e85b11192a07.png)
这里选择的是北京--北京东城
加载数据后会显示id，需要手动展开北京后才能显示为北京东城
![image](https://user-images.githubusercontent.com/35142778/165426072-792901a4-31cc-4753-aefe-d2771f2f7516.png)

**Comment by yujinpan** [comment]
`render-after-expand` 用于配置是否在展开节点时进行渲染，试着将它设为否：

```vue
<el-select-tree :render-after-expand="false"></el-select-tree>
```

参考文档：https://element.eleme.io/#/zh-CN/component/tree#attributes

**Comment by Montaro2017** [comment]
已解决

**Comment by huang-yaoshi** [comment]
@Montaro2017   您好 问一下 你这边怎么解决的？

**Comment by Montaro2017** [comment]
> 

实际上没解决，只不过因为我们的数据是固定的，所以把数据放到前端了，就不需要懒加载了

**Comment by Montaro2017** [comment]
> @Montaro2017 您好 问一下 你这边怎么解决的？

实际上没解决，只不过因为我们的数据是固定的，所以把数据放到前端了，就不需要懒加载了

**Comment by Montaro2017** [comment]
> @Montaro2017 您好 问一下 你这边怎么解决的？

如果非要一个解决方案的话，我觉得可以后端将id和名称给前端，前端先渲染后端给出的名称，然后点击展开加载数据再去使用懒加载的数据

**Comment by huang-yaoshi** [comment]
> > @Montaro2017 您好 问一下 你这边怎么解决的？

好的 那我这边还是转一下吧  谢谢啦

**Comment by huang-yaoshi** [comment]
> `render-after-expand` 用于配置是否在展开节点时进行渲染，试着将它设为否：
> 
> ```
> <el-select-tree :render-after-expand="false"></el-select-tree>
> ```
> 
> 参考文档：https://element.eleme.io/#/zh-CN/component/tree#attributes

这个对于懒加载数据的  没有用呀

**Comment by yujinpan** [comment]
懒加载的数据可以设置默认展开的id包含所有父集的id。
