### ISSUE TITLE
升级到2.0.9之后，change事件会触发两次

### ISSUE THREAD

**Issue by zhoufenfens** [yujinpan/el-select-tree#46]
您好，升级到2.0.9之后，解决了expand-on-click-node不生效的问题，但是发现另一个bug，change事件触发了两次， 版本回退到2.0.5，没有这个问题，貌似从2.0.7开始之后就存在这个问题。

**Comment by yujinpan** [comment]
感谢反馈，2.0.10 中已修复。

**Comment by zhoufenfens** [comment]
> 感谢反馈，2.0.10 中已修复。

谢谢。已验证。
