### ISSUE TITLE
请问大佬有JS版的吗？想基于您的版本改一下写个功能，但是不太会TS，看不懂 (抱歉)。

### ISSUE THREAD

**Issue by oubaguilai** [yujinpan/el-select-tree#47]
![image](https://user-images.githubusercontent.com/24708305/179356963-74e9ad7a-ae11-43fe-8812-6ec75192f78d.png)

**Comment by yujinpan** [comment]
没有 js，如果不熟悉可以刚好练习一下，ts 是以后的趋势。

:D

**Comment by oubaguilai** [comment]
好的，谢谢

**Comment by djkloop** [comment]
> 好的，谢谢

```sh
https://codesandbox.io/s/element-ui-2brgmd?file=/src/App.vue
```
我这有一个你可以看看。
@oubaguilai
