### ISSUE TITLE
通过setCheckedKeys设置选中节点不起作用

### ISSUE THREAD

**Issue by canmeng** [yujinpan/el-select-tree#49]
![image](https://user-images.githubusercontent.com/15072609/191688178-97b8cf59-068b-4a6a-bfc2-a48901d1d059.png)

**Comment by canmeng** [comment]
已经设置了node-key

**Comment by yujinpan** [comment]
https://github.com/yujinpan/el-select-tree/issues/50#issuecomment-1296901255
