### ISSUE TITLE
不能使用clearable吗？

### ISSUE THREAD

**Issue by simonkes** [yujinpan/el-select-tree#5]
不能使用clearable吗？

**Comment by yujinpan** [comment]
Hi，`clearable` 已加上。
`props`文档：https://github.com/yujinpan/el-select-tree#attributes
在线实例：https://yujinpan.github.io/el-select-tree/

**Comment by simonkes** [comment]
效率太高了吧 ，嘿嘿

**Comment by yujinpan** [comment]
🤓
