### ISSUE TITLE
defaultChecked keys is not working 

### ISSUE THREAD

**Issue by SaiKiranRebba** [yujinpan/el-select-tree#50]

**Comment by SaiKiranRebba** [comment]
@yujinpan please help

**Comment by yujinpan** [comment]
Hey, the checked nodes are bound to `v-model/value`. Please set the model value.

**Comment by SaiKiranRebba** [comment]
yeah @yujinpan  it worked. Thanks for the help

**Comment by SaiKiranRebba** [comment]
if we v-model is an object then its not working as expeceted @yujinpan

**Comment by yujinpan** [comment]
> 

Object types are currently not supported, you can create corresponding properties on the node to achieve this function:

```tsx
const data = [
  { value: 1, obj: {} }
];
const obj = {};
const vlaue = treeFind(data, node => node.obj === obj)?.value;

const render = () => <el-select-tree vModel={value} data={data} />

function treeFind(data, callback) {}
```
