### ISSUE TITLE
数据量稍微一多了多选回显就很卡

### ISSUE THREAD

**Issue by zhoubapi999** [yujinpan/el-select-tree#51]
在npm 2.0.14版本下，多选且开启checkbox情况下，数据稍微大点选中回显就很卡顿
在1.1.3下倒是不卡，但是有明显bug

**Comment by yujinpan** [comment]
感谢反馈，尽快修复！

**Comment by Krue1** [comment]
我发现卡顿的原因都是script在耗时，应该是value转label各种遍历树的耗时，我再读了一下文档，发现有cache-data这个prop供未加载出的节点去转label的，我在想是不是可以在保存时把选中的option都保存起来，然后树使用懒加载，是否可以解决这个卡顿的问题呢

**Comment by zhoubapi999** [comment]
我之前是回退到2.0.6版本就不卡了

**Comment by Krue1** [comment]
> 我之前是回退到2.0.6版本就不卡了

可是这个版本会有bug，树的checkbox没有勾上，恼啊~

**Comment by Krue1** [comment]
> 我发现卡顿的原因都是script在耗时，应该是value转label各种遍历树的耗时，我再读了一下文档，发现有cache-data这个prop供未加载出的节点去转label的，我在想是不是可以在保存时把选中的option都保存起来，然后树使用懒加载，是否可以解决这个卡顿的问题呢

突然想到这个方案对我可能也不适用，我是在一个页面可以同时存在很多个这个select-tree组件，用的treeData是同一个

**Comment by yujinpan** [comment]
已在 2.0.17 中修复。

**Comment by iuxw** [comment]
2.0.17 共计200条数据，多选勾选时要卡顿3s左右

**Comment by viarotel** [comment]
> > 2.0.17 共计200条数据，多选勾选时要卡顿3s左右
> 
> 已在 2.0.18 中修复。

2.0.18 依然存在这个问题

**Comment by yujinpan** [comment]
> > > 2.0.17 共计200条数据，多选勾选时要卡顿3s左右
> > 
> > 
> > 已在 2.0.18 中修复。
> 
> 2.0.18 依然存在这个问题

请提供下使用实例，我测试了2w节点没有卡顿哦。

**Comment by huzedong2015** [comment]
check-strictly 设置这个后选第一级的数据就非常卡顿了

**Comment by yujinpan** [comment]
> check-strictly 设置这个后选第一级的数据就非常卡顿了， 数据量并不大 不到100条。 复现： 第一级有个20条数据， 第一级的子元素有20个。选择就出现卡顿了。

请提供下使用实例。

**Comment by huzedong2015** [comment]
> > check-strictly 设置这个后选第一级的数据就非常卡顿了， 数据量并不大 不到100条。 复现： 第一级有个20条数据， 第一级的子元素有20个。选择就出现卡顿了。
> 
> 请提供下使用实例。

https://codesandbox.io/s/admiring-http-n3lhpr?file=/src/App.vue

**Comment by yujinpan** [comment]
> 如果我批量设置这些值会明显卡顿

已在 v2.0.20 中优化，请更新测试

**Comment by huzedong2015** [comment]
目前在v2.0.20可以了
