### ISSUE TITLE
This package support filter-node-method prop or not ?

### ISSUE THREAD

**Issue by SaiKiranRebba** [yujinpan/el-select-tree#53]

**Comment by SaiKiranRebba** [comment]
@yujinpan could you please help here. Whether filter-node-method prop will work or not. I tried but its not working

**Comment by yujinpan** [comment]
Hey, take a look at the code example.

**Comment by SaiKiranRebba** [comment]
I tried but its not working and i have already looked into the examplese aswell https://yujinpan.github.io/el-select-tree/ . Can u please guide me to that place

**Comment by SaiKiranRebba** [comment]
codesandbox created for filterNodeMethod . https://codesandbox.io/s/intelligent-kate-8hczdu?file=/src/App.vue. Its not even going to that method

**Comment by yujinpan** [comment]
`filterNodeMethod` need to return an value.

https://codepen.io/pen

**Comment by SaiKiranRebba** [comment]
@yujinpan return is there , still no luck https://codesandbox.io/s/reverent-wood-50cpu2?file=/src/App.vue

**Comment by yujinpan** [comment]
Sorry, this issue has been fixed in v2.0.16, please update.

**Comment by SaiKiranRebba** [comment]
working fine after updating the version. Thanks @yujinpan
