### ISSUE TITLE
节点数量多的情况下，首次渲染会很慢

### ISSUE THREAD

**Issue by ignaceshi** [yujinpan/el-select-tree#54]
会出现卡很久空白的情况
如果去除node-key就会很快
麻烦作者有空修复下。感谢~

**Comment by yujinpan** [comment]
感谢反馈！请问当前数据量有多大，我便于测试还原问题。

**Comment by ignaceshi** [comment]
总计 5238 个节点。
我观察了一下，可能是绑定值转换为label会比较慢。

**Comment by yujinpan** [comment]
已在 2.0.17 中修复。
