### ISSUE TITLE
core-js依赖安装失败

### ISSUE THREAD

**Issue by Krue1** [yujinpan/el-select-tree#57]
查看安装依赖后的源码路径`/lib/components/ElSelectTree.js`的第19、20行

```javascript
import 'core-js/modules/es.error.cause.js';
import 'core-js/modules/es.array.push.js';
```

这两个js文件我翻了很多core-js版本，都不存在，导致build的时候会出现module not found的情况，请问作者这个怎么解决呢

**Comment by yujinpan** [comment]
试下:

```sh
npm i core-js@3.28.0
```

**Comment by Krue1** [comment]
> 试下:
> 
> ```shell
> npm i core-js@3.28.0
> ```

十分感谢，已经解决，果然还得更高的core-js版本，这core-js major不变就有breaking change
