### ISSUE TITLE
能开放一个下拉弹窗框顶部的slot吗

### ISSUE THREAD

**Issue by huzedong2015** [yujinpan/el-select-tree#64]
我想在顶部加一些自定义的功能目前没办法实现

**Comment by huzedong2015** [comment]
![image](https://github.com/yujinpan/el-select-tree/assets/14806813/bcbf0b28-720b-488c-9549-e804bdacc5ce)

**Comment by yujinpan** [comment]
这种定制化高的还得自己实现哦。
