### ISSUE TITLE
虚拟列表开启过滤搜索，搜索子级，父级没有展开

### ISSUE THREAD

**Issue by czq297297** [yujinpan/el-select-tree#69]
虚拟列表开启过滤搜索，搜索子级，父级没有展开

**Comment by yujinpan** [comment]
由于当前的一些性能问题，仅展开搜索到的第一个，更新至 2.1.1-beta.3 使用。

**Comment by czq297297** [comment]
感觉还是没有解决问题  能否加一个props 配置是否开启搜索子级父级自动展开
