### ISSUE TITLE
多选时，怎么才能获取到选择的当前节点的value

### ISSUE THREAD

**Issue by melyao** [yujinpan/el-select-tree#7]
如果当前节点有子节点，返回的是当前节点下面的子节点的value，我的需求是只要当前节点value

**Comment by yujinpan** [comment]
Hi，感谢反馈，我在新版本中修复了这个问题，请更新版本。
并且你使用多选下的【父子节点不关联】需要 `check-stricktly = true`，请使用该 props。

查看在线实例：https://yujinpan.github.io/el-select-tree/
查看 props 文档：https://github.com/yujinpan/el-select-tree#attributes
