### ISSUE TITLE
虚拟滚动选择树el-select-tree-virtual，多选时个数超过缓冲区大小会出现选择丢失问题

### ISSUE THREAD

**Issue by wodesyjh** [yujinpan/el-select-tree#74]
第一步：选择test1、test2、test3
第二步：滚动到下面选择test500时，原来选择的test1，test2，test3就会丢失
代码如下
```vue
<template>
  <div>
    use checkbox:
    <ElSelectTreeVirtual
      v-model="value"
      multiple
      :data="data"
      check-strictly
      show-checkbox
    ></ElSelectTreeVirtual>
  </div>
</template>

<script>
import { ElSelectTreeVirtual } from 'el-select-tree';
export default {
  components: {
    ElSelectTreeVirtual,
  },
  mounted() {
    const temp = []
    for (let i = 0; i < 1000; i++) {
      temp.push({
        label: '测试' + i,
          value: i + '',
      })
    }
    this.data.push(...temp)
  },
  methods: {},
  data() {
    return {
      value: '',
      data: [],
    };
  },
};
</script>
```

**Comment by huzedong2015** [comment]
应该和数据量大小没关系20个也可以复现

https://github.com/yujinpan/el-select-tree/assets/14806813/a0befb1f-ab3e-470f-9dc6-f1c574fa46f7

复现：

1. 选择第一个和第二个
2. 滚动换页直到选择内容不出现
3. 随便选择一个

**Comment by huzedong2015** [comment]
@yujinpan 不行更严重了。选择直接报错了。
![image](https://github.com/yujinpan/el-select-tree/assets/14806813/f8b29957-1438-47d7-8f1c-6ab4bc318023)

**Comment by wodesyjh** [comment]
> Fixed in 2.1.1-beta.7
![image](https://github.com/yujinpan/el-select-tree/assets/48074316/1ec89268-95d9-4991-b9fa-7c5ed8569ecc)
会出现选择不上的情况

**Comment by wodesyjh** [comment]
https://github.com/yujinpan/el-select-tree/assets/48074316/c16337a6-9b59-466d-ba20-ea1fb7022b17

增加clearable属性清除选择有bug

**Comment by yujinpan** [comment]
`clearable` has been fixed in 2.1.1-beta.9.
