### ISSUE TITLE
我升级包到2.1.1-beta.10版本报错了  之前是好的 需要vue版本2.7以上吗？ 我现在是2.6.10版本

### ISSUE THREAD

**Issue by baihuijun** [yujinpan/el-select-tree#80]
![Snipaste_2024-05-09_14-02-21](https://github.com/yujinpan/el-select-tree/assets/52630363/40f425a5-4810-4165-afdf-340c3610e99c)
![Snipaste_2024-05-09_14-02-48](https://github.com/yujinpan/el-select-tree/assets/52630363/57f3feb9-692c-4791-babb-9d2b53138579)
![Snipaste_2024-05-09_14-03-12](https://github.com/yujinpan/el-select-tree/assets/52630363/fa8eeaa1-c32e-406d-9615-f55fac2f307b)

**Comment by yujinpan** [comment]
2.1.1-beta.11 中已修改，兼容 2.6。
