### ISSUE TITLE
目前的搜索filterable是精确匹配 , 纯小写或者纯大写匹配不到

### ISSUE THREAD

**Issue by shiloh-xin** [yujinpan/el-select-tree#81]
![QQ截图20240514180745](https://github.com/yujinpan/el-select-tree/assets/72586120/f4321ead-4cf6-43e5-9a68-03f49f619fa6)
![QQ截图20240514180759](https://github.com/yujinpan/el-select-tree/assets/72586120/7a2d32a7-9ac1-414b-b4c2-f71e5e666556)
![QQ截图20240514180812](https://github.com/yujinpan/el-select-tree/assets/72586120/a1fd57cb-b988-4949-bfd7-da16c43b76e3)

**Comment by shiloh-xin** [comment]
临时解决办法如下 :  希望作者可以优化一下 , 版本2.0.20 ( 2.1安装会报错 ) 

:filter-node-method="filterNode"

filterNode(value, data) {
      if (!value) return true
      let nowVal = data.name.toUpperCase()
      return nowVal.indexOf(value.toUpperCase()) !== -1
   }

**Comment by yujinpan** [comment]
2.1.1-beta.11 中已修改安装报错问题，兼容 2.6。

**Comment by yujinpan** [comment]
大小写匹配在 2.1.1-beta.15 中已修改。
