### ISSUE TITLE
虚拟树，进行搜索时，滚动太快会显示无数据

### ISSUE THREAD

**Issue by myqianlan** [yujinpan/el-select-tree#82]
官方demo也有这个问题

**Comment by yujinpan** [comment]
已在 v2.1.1-beta.12 中修复。

**Comment by myqianlan** [comment]
> 已在 v2.1.1-beta.12 中修复。

问题还是存在。
复现方式：
可搜索的虚拟树，输入99，然后向下快速滚动即可复现

**Comment by yujinpan** [comment]
https://github.com/yujinpan/el-select-tree/assets/20787785/0038c78b-69f7-4a18-ba74-425d7f796535

**Comment by myqianlan** [comment]
https://github.com/yujinpan/el-select-tree/assets/5117885/674c8c9a-e1b9-4b55-ae36-e6fcc7e35b5e
