### ISSUE TITLE
Package path ./helpers/esm/callSuper is not exported from package

### ISSUE THREAD

**Issue by kooriookami** [yujinpan/el-select-tree#84]
![image](https://github.com/yujinpan/el-select-tree/assets/38392315/b034c04e-df7a-441f-84d2-f57876c9ee7a)
我看了下，是这个模块的引用不存在，导致报错了，这一行代码是2.1.1-beta.14版本中添加的

**Comment by yujinpan** [comment]
@babel/runtime 版本可能不一致，package.json 中没有锁定版本

https://github.com/yujinpan/el-select-tree/blob/a4fff8210154a08c48773441b6a11997b01c144e/package-lock.json#L2058-L2059

**Comment by yujinpan** [comment]
在 2.1.1-beta.15 中已修改。
